<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>NHL Shot Analysis – Seth Kaufman’s Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

<script src="site_libs/datatables-binding-0.34.0/datatables.js"></script>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

<link href="site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

<script src="site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Seth Kaufman’s Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research Reports</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-research-reports">    
        <li>
    <a class="dropdown-item" href="./Research_Report_1.html">
 <span class="dropdown-text">Bias &amp; Variance Tradeoff and BLUE</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Research_Report_2.html">
 <span class="dropdown-text">Ensemble Learning Techniques for Fair Classification</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="./Applied_Probability_Die_Roll.html">
 <span class="dropdown-text">Conditional Probability Problem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Congestion_Pricing_TS1.html">
 <span class="dropdown-text">Congestion Pricing Time Series Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Electoral_Process.html">
 <span class="dropdown-text">Electoral College Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Home_Pricing_Competition.html">
 <span class="dropdown-text">Home Pricing Prediction Competition</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NHL_Shot_Analysis_TS.html">
 <span class="dropdown-text">NHL Shot Attempts Time Series Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NHL Shot Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>A popular sport in both North America and Europe, ice hockey is considered one of the fastest and most difficult team games to play.</p>
<p>In North America, the largest ice hockey league is the <em>National Hockey League</em> or <em>NHL</em>. It is a league comprised of 32 teams, 25 in the U.S. and 7 in Canada, all of whom compete each year to lift what some consider the greatest trophy in sports, the Stanley Cup.</p>
<div class="center-image" style="text-align: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ts1/barkov_cup_lift.png" class="img-fluid figure-img"></p>
<figcaption>Panthers captain Aleksander Barkov lifts Cup in 2024, via AP News</figcaption>
</figure>
</div>
</div>
<p>The basic rules of hockey are as follows:</p>
<ul>
<li>Each team can have a maximum of 5 players plus a goaltender on the ice at any given time
<ul>
<li>This can change based on whether a team has taken a penalty (infraction), or has pulled their goaltender for an extra attacked</li>
</ul></li>
<li>You win by scoring more goals than the other team
<ul>
<li>A goal is when the puck, the small black object made of vulcanized rubber, crosses the goal line and into the net</li>
<li>There is an exception to this rule in the regular season, you can win in a shootout, which doesn’t count as a goal</li>
</ul></li>
</ul>
<div class="center-image" style="text-align: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ts1/martinook_playoff_save.png" class="img-fluid figure-img"></p>
<figcaption>Hurricanes forward Jordan Martinook keeping the puck out of the net in the 2024 playoffs, via SportsNet on YouTube</figcaption>
</figure>
</div>
</div>
</section>
<section id="goals-and-shot-attempts" class="level1">
<h1>Goals and Shot Attempts</h1>
<p>So, how does a team score a goal?</p>
<p>The most standard way is to take a shot from somewhere, most often in the offensive/attacking zone. When a player takes a shot, it registers as a <em>shot attempt</em> (<em>SA</em>). When a shot attempt is placed on net, it counts as a <em>shot on goal</em> (<em>SoG</em>), and when it goes into the goal, it’s counted as a <em>goal</em> or <em>goal for</em> (<em>GF</em>).</p>
<p>The first <em>gif</em> below shows a shot attempt that is also a shot on goal and a goal for.</p>
<figure style="text-align: center;" class="figure">
<img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExemNpbW5yaHl0ejhycmE1dDJzeWp5ZHlndHZtdHM5OXd4NmtxMGNzaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/22DTizzirZseyvTn2t/giphy.gif" alt="Weber Slapshot" class="figure-img">
<figcaption>
A shot attempt, a shot on goal and a goal for. Credit anonymous on Giphy
</figcaption>
</figure>
<p>The second <em>gif</em> shows a shot attempt that was blocked by a defender and is therefore only a shot attempt, not a shot on goal.</p>
<figure style="text-align: center;" class="figure">
<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWpubm82Nmo2dHZrMDQwNGJmc3huODh2a2htNm5xOXRwdmhqNG5xMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/13eFj2I8TE3YY/giphy.gif" alt="Landeskog Wristshot" class="figure-img">
<figcaption>
A shot attempt, but not a shot on goal. Credit <span class="citation" data-cites="hockeyplayersclub">@hockeyplayersclub</span> on Giphy
</figcaption>
</figure>
</section>
<section id="project-motivation" class="level1">
<h1>Project Motivation</h1>
<p>Any fan of the NHL might have heard the term <em>shot attempt</em>, especially from the last few years, as broadcasting networks such as <em>ESPN</em> have talked about them <em>ad nauseum</em> as a be-all-end-all offensive statistic.</p>
<p>As a New York Rangers fan, I especially began to notice the term being used in reference to the Carolina Hurricanes, a team whom the Rangers have played twice in the playoffs in the past 3 years (2022 and 2024). The Hurricanes would frequently have double or triple the number of shot attempts as the Rangers, however…</p>
<figure style="text-align:center; padding:10px; border-radius:8px;" class="figure">
<img src="images/ts1/Rangers_2022_Win.png" height="200px" style="margin-right:10px;" class="figure-img"> <img src="images/ts1/Rangers_2024_Win.png" height="200px" class="figure-img">
<figcaption style="color:black; font-style:italic; margin-top:8px;">
Sorry not sorry, Hurricanes fans (via SportsNet on YouTube)
</figcaption>
</figure>
<p>However, neither the Rangers nor the Hurricanes were the primary motivation for this analysis. It’s actually the Florida Panthers, the current reigning back-to-back Stanley Cup champions.</p>
<p>The Florida Panthers have made the Stanley Cup Final for the past 3 years, losing the first year to Vegas, then winning the past two against Edmonton both times. After making the Final for the third consecutive season by beating the Carolina Hurricanes in the Eastern Conference Final in 5 games, Hurricanes coach Rod Brind’Amour said <a href="https://www.sportsnet.ca/nhl/video/hurricanes-brindamour-sees-panthers-style-of-play-as-the-standard/">“[The Florida Panthers] are the standard”</a>.</p>
<p>The Panthers are a team that prides itself on a two-way game, being effective in all-three zones. In the offensive zone, that includes getting shots to the net. The NHL is a copycat league, as are most in the sports world. This leads me to analyzing Shot Attempts as a metric and trying to forecast shot attempts throughout the year in a standard, 82 game regular season.</p>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p>To analyze this, I used <a href="https://moneypuck.com/data.htm">MonkeyPuck.com data</a>. Specifically, their game data which has tracked NHL games since the 2008 season.</p>
<p>For this project, I will only look at data from the 2021 season (which began on October 12, 2021) through the beginning of the 2025 (current) season, with the most recent data as of October 28, 2025, excluding all playoffs.</p>
<p>The reasons for this specific stratification are:</p>
<ul>
<li>This is reasonably recent data</li>
<li>The 2021-22 season is when the NHL expanded to its current number of 32 teams with the addition of the <code>Seattle Kraken</code></li>
<li>This was the first full-length, 82 game season following the 2020-21 COVID Pandemic
<ul>
<li>Each season has been 82 regular season games for each team</li>
</ul></li>
<li>All 32 teams played 82 games in the 4 seasons of training data (<span class="math inline">\(32 \times 82 \times 4 = 10,496\)</span> total games)
<ul>
<li>Each team has played a minimum of <span class="math inline">\(8\)</span> games in the 2025 season which can be used as testing data for Time Series forecasting</li>
<li>As a note, the <code>Arizona Coyotes</code> moved to Utah for the 2024 season, so the <code>Arizona Coyotes</code>, the <code>Utah Hockey Club</code> and the <code>Utah Mammoth</code> are all counted as the same franchise for the purpose of this analysis</li>
</ul></li>
</ul>
<section id="raw-data" class="level2">
<h2 class="anchored" data-anchor-id="raw-data">Raw Data</h2>
<p>The below data has been filtered and had some renaming done for visual purposes, but is more-or-less the raw data that was pulled from MoneyPuck.</p>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-a75cfdf475bd2d3c8518" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-a75cfdf475bd2d3c8518">{"x":{"filter":"none","vertical":false,"data":[["Detroit Red Wings","New York Rangers","Carolina Hurricanes","Florida Panthers","Minnesota Wild","Utah Mammoth"],[2021,2021,2023,2023,2025,2025],[2021021201,2021021201,2023020205,2023020205,2025020131,2025020131],["2022-04-16","2022-04-16","2023-11-10","2023-11-10","2025-10-25","2025-10-25"],[37,68,69,60,75,62]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Team<\/th>\n      <th>Season<\/th>\n      <th>Game_ID<\/th>\n      <th>Date<\/th>\n      <th>ShotAttempts_For<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"tip","pageLength":6,"columnDefs":[{"className":"dt-right","targets":[1,2,4]},{"name":"Team","targets":0},{"name":"Season","targets":1},{"name":"Game_ID","targets":2},{"name":"Date","targets":3},{"name":"ShotAttempts_For","targets":4}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[6,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing">Data Preprocessing</h2>
<p>For the temporal component of this analysis, I aggregated all of the <code>ShotAttempts_For</code> for each team across each <code>game_number</code>.</p>
<p>What this means is, for each team’s game 1, or game 2, 3… 82 (e.g.: <span class="math inline">\(gameNumber \in [1-82]\)</span>), we take the average of all 32 teams in each season and count that.</p>
<p>So as an example, below we see the first game of each season (excluding 2025 since it’s not included in the training data) for the <em>Los Angeles Kings</em>:</p>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-ce8e2346bc0808cc37c0" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-ce8e2346bc0808cc37c0">{"x":{"filter":"none","vertical":false,"caption":"<caption style=\"caption-side: bottom; text-align: left;\">LAK — Game 1 detail by season, with summary mean/SD row<\/caption>","data":[["LA Kings","LA Kings","LA Kings","LA Kings","LA Kings"],["2021","2022","2023","2024","Summary"],["2021-10-14","2022-10-11","2023-10-11","2024-10-10",null],[84,56,73,48,null],[null,null,null,null,65.2],[null,null,null,null,16.3]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Team<\/th>\n      <th>Season<\/th>\n      <th>Date<\/th>\n      <th>ShotAttempts_For<\/th>\n      <th>Mean_ShotAttempts_For<\/th>\n      <th>StDev_ShotAttempts_For<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"tip","pageLength":5,"columnDefs":[{"className":"dt-right","targets":[3,4,5]},{"name":"Team","targets":0},{"name":"Season","targets":1},{"name":"Date","targets":2},{"name":"ShotAttempts_For","targets":3},{"name":"Mean_ShotAttempts_For","targets":4},{"name":"StDev_ShotAttempts_For","targets":5}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>So, across the four <span class="math inline">\(GameNumber=1\)</span> for the <em>Los Angeles Kings</em>, <span class="math inline">\(\mu\approx65.2\)</span> and <span class="math inline">\(\sigma\approx16.3\)</span>.</p>
<p>Doing this for every team, then averaging those values, we get the following:</p>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-d37419994fcaa17e7f1d" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-d37419994fcaa17e7f1d">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5"],[1,24,55,81,82],[60.17,58.52,60.12,58.5,57.82],[12.21,12.1,11.51,12.96,11.81],[128,128,128,128,128]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Game_Number<\/th>\n      <th>Avg_ShotAttempts_For<\/th>\n      <th>StDev_ShotAttempts_For<\/th>\n      <th>Number_of_Observations<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"tip","pageLength":5,"columnDefs":[{"className":"dt-right","targets":[1,2,3,4]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Game_Number","targets":1},{"name":"Avg_ShotAttempts_For","targets":2},{"name":"StDev_ShotAttempts_For","targets":3},{"name":"Number_of_Observations","targets":4}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>There are <span class="math inline">\(128\)</span> occurances of each game number (<span class="math inline">\(32 \times 4\)</span>).</p>
</section>
</section>
<section id="eda" class="level1">
<h1>EDA</h1>
<p>Before performing any Time Series modeling, I wanted to see if we could gain any other insights from the data, including its distribution.</p>
<section id="shot-attempt-volume" class="level2">
<h2 class="anchored" data-anchor-id="shot-attempt-volume">Shot Attempt Volume</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/eda[4]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>This <code>stacked bar/proportion</code> chart gives us an idea of the volume of <code>shot attempts</code>.</p>
</section>
<section id="top-10" class="level2">
<h2 class="anchored" data-anchor-id="top-10">Top 10</h2>
<p>Next I looked at <code>shots on goal</code> to <code>shot attempts</code> and <code>goals for</code> to <code>shot attempts</code> and ranked the top 10 in each, along with their respective win % (how many Regulation/OT Wins, not including shootout wins).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/wins[5]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>It’s interesting that <code>shots on goal / shot attempts</code> tends to favor teams with some of the worse win percentages, while <code>goals for / shot attempts</code> seems to favor the better teams, and other than the Buffalo Sabres, the teams that are top 10 in both metrics tend to be some of the better teams in the league.</p>
</section>
<section id="shot-attempt-distribution" class="level2">
<h2 class="anchored" data-anchor-id="shot-attempt-distribution">Shot Attempt Distribution</h2>
<p>The below histogram and tests show the distribution of <code>shot attmepts</code> over a :</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/distribution[6]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The distribution looks to be fairly normal.</p>
<p>Running a few tests we can ensure the data is normally distributed, as well as look at its skew.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  df_team_totals$ShotAttemptsFor
W = 0.97291, p-value = 0.5832</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2875302</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1121519</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Goodness-of-fit statistics
                             1-mle-norm 2-mle-gamma 3-mle-lnorm
Kolmogorov-Smirnov statistic 0.11073958  0.11608965  0.11944849
Cramer-von Mises statistic   0.06265581  0.06109229  0.06102607
Anderson-Darling statistic   0.38101859  0.36336270  0.35935704

Goodness-of-fit criteria
                               1-mle-norm 2-mle-gamma 3-mle-lnorm
Akaike's Information Criterion   551.3926    551.0638    550.9657
Bayesian Information Criterion   554.3241    553.9953    553.8972</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/tests[7]-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <code>Shapiro-Wilkes Test</code> returned a <span class="math inline">\(p-value \approx 0.58\)</span>, so we can conclude the <span class="math inline">\(H_0\)</span> of its test that the data is normally distributed.</p>
<p>The <code>skewness</code> test returned <span class="math inline">\(0.29\)</span> showing a slightly-positive (right-tailed) skew, but nothing completely out of the ordinary, while the <code>kurtosis</code> test returned <span class="math inline">\(-0.11\)</span>, slightly lower than a normal distribution at <span class="math inline">\(0\)</span>, but practically normal.</p>
<p>The <code>Kolmogorov-Smirnov</code> statistic shows that the normal distribution’s <span class="math inline">\(CDF\)</span> fits the data best. Both the <code>CvM</code> and <code>Anderson-Darling</code> statistics show the other distributions might be marginally better, but since the difference is marginal, a normal distribution likely still fits the data best and at the very least most simply.</p>
<p>The <code>AIC</code> and <code>BIC</code> figures while technically favoring the other types of distributions, really don’t show a significant statistical difference between the three.</p>
<p>Finally, the diagnostic plots also confirm normally distributed data. Although we see some slight skew, these all confirm the data is fairly normally distributed.</p>
<p>We can also expect that as more game data is added, this distribution will likely become more normal over time.</p>
<p>This matters for our eventual time series modelling as it hints that the residuals might be normal as well, meaning the model’s error term behaves like white noise where <span class="math inline">\(w_t\sim wN(0,\sigma^2_w)\)</span>.</p>
</section>
</section>
<section id="time-series-modeling" class="level1">
<h1>Time Series Modeling</h1>
<p>Finally, the good stuff.</p>
<p>Below is a <code>Time Series</code> plot of the average shot attempts across the four training-data seasons (2021-2024) for each game 1-82.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/tests[8]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>This chart shows a fairly stable time series with random fluctuations and no visible seasonality component.</p>
<section id="stationarity" class="level2">
<h2 class="anchored" data-anchor-id="stationarity">Stationarity</h2>
<p>Using R’s functionality, we can make some stationarity checks and use <code>ndiffs</code> to see if an <code>ARIMA(p,d,q)</code> model might make sense.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  y
Dickey-Fuller = -7.0972, Lag order = 0, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
</div>
<p>The <code>Augmented Dickey-Fuller</code> test for stationarity returned a <span class="math inline">\(p-value&lt;\alpha\)</span> where <span class="math inline">\(\alpha = 0.05\)</span>, concluding the <span class="math inline">\(H_a:Stationarity\)</span>.</p>
<p>The <code>ndiffs</code> function returns the recommended <em>regular differences</em> <code>d</code> needed to make the series stationary. Returning <span class="math inline">\(d=0\)</span> means that none are needed and some sort of <span class="math inline">\(ARMA(p,q)\)</span> model can be used.</p>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model Selection</h2>
<p>We can use the <code>auto.arima</code> function with params <code>d=0</code>, <code>max.p=12</code> and <code>max.q=12</code> to test different <code>ARMA(p,q)</code> models with parameters <span class="math inline">\(p \in [0,12]\)</span> and <span class="math inline">\(q \in [0,12]\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/arma[10]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The <code>Q-Q Plot</code> shows the residuals are almost exactly normally distributed. The model captures virtually all non-white noise data very well.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/residuals[11]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(1,0,0) with non-zero mean
Q* = 7.9388, df = 9, p-value = 0.5403

Model df: 1.   Total lags used: 10</code></pre>
</div>
</div>
<p>We can see one small lag spike around <span class="math inline">\(k=11\)</span>, but everything looks reasonable with this.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: y_ts 
ARIMA(1,0,0) with non-zero mean 

Coefficients:
         ar1     mean
      0.2284  58.7863
s.e.  0.1092   0.1236

sigma^2 = 0.77:  log likelihood = -104.65
AIC=215.31   AICc=215.61   BIC=222.53

Training set error measures:
                       ME      RMSE       MAE         MPE     MAPE      MASE
Training set -0.004306545 0.8667462 0.7046645 -0.02903882 1.198698 0.7736908
                    ACF1
Training set -0.01303734</code></pre>
</div>
</div>
<p>The model’s output returns <span class="math inline">\(\mu=58.78\)</span> and an <span class="math inline">\(AR(1)\)</span> parameter of <span class="math inline">\(\phi \approx 0.22\)</span>, which is the preferred model type for this data.</p>
<p>An <span class="math inline">\(AR(1)\)</span> model has the following equation:</p>
<p><span class="math inline">\(x_t=c+\phi x_{t-1}+w_t\rightarrow58.78+0.22(Bx-58.78)+w_t\approx 45.84+Bx+w_t\)</span></p>
</section>
<section id="forecasting" class="level2">
<h2 class="anchored" data-anchor-id="forecasting">Forecasting</h2>
<p>With an <span class="math inline">\(AR(1)\)</span> model that uses the full 2021-2024 seasons as training data, we can use the testing data that is the first 8 games of the 2025 season to see how well it can forecast what’s happened already this season.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/forecast[13]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>A more zoomed-in look at the forecast:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NHL_Shot_Analysis_TS_files/figure-html/forecastZoom[14]-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Other than the point at <span class="math inline">\(gameNumber=4\)</span>, all of the points fall within the <span class="math inline">\(95\%\)</span> Confidence Interval of the forecasted section. This <span class="math inline">\(AR(1)\)</span> model really fits the data extremely well.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.165243</code></pre>
</div>
</div>
<p>Checking the <em>Test RMSE</em> for good measure, a value of <span class="math inline">\(\approx 1.17\)</span> shows that the model’s <code>shot attempt</code> forecast is about <span class="math inline">\(\pm 1.17\)</span> on average, which translates to the average model prediction being about <span class="math inline">\(\frac {1.17} {57.89} \approx 0.02 \rightarrow 2\%\)</span> off.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>After testing the data itself for normality, followed by the residuals of the best-fit model, we have a <em>weakly stationary</em> <span class="math inline">\(AR(p=1)\)</span> model with parameters <span class="math inline">\(\phi = 0.22\)</span> and <span class="math inline">\(\mu=58.79\)</span>, which returned an equation of <span class="math inline">\(x_t = 45.84+Bx+w_t\)</span>. It has a stable mean and variance, so a time series model suits the data well.</p>
<p>It was able to forecast decently well, with <span class="math inline">\(7/8\)</span> of the test points falling within the <span class="math inline">\(95\%\)</span> confidence interval of the forecast line, with the one outlier being barely outside of it.</p>
<section id="next-steps" class="level2">
<h2 class="anchored" data-anchor-id="next-steps">Next Steps</h2>
<p>Potential next-steps for this project include:</p>
<ul>
<li>Creating a dashboard with game forecasts and using it to update <code>gameNumber</code> averages as the season goes on</li>
<li>Figure out a way to include playoffs</li>
<li>Use regression analysis to see if Shot Attempts are increasing or staying the same</li>
</ul>
</section>
<section id="do-the-gritty" class="level2">
<h2 class="anchored" data-anchor-id="do-the-gritty">Do the Gritty</h2>
<figure style="text-align: center;" class="figure">
<img src="https://media.giphy.com/media/Qv4Jw8utQgYTUKnyo6/giphy.gif" alt="Gritty" class="figure-img">
<figcaption>
When you stare into the void, the void stares back. Credit NHL on Giphy
</figcaption>
</figure>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/SethKauf\.github\.io\/Portfolio\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>